<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<configuration>
		<source>25</source>
		<target>25</target>
		<release>25</release>
		<!-- THIS PART IS CRITICAL -->
		<annotationProcessorPaths>
			<path>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.32</version>
			</path>
		</annotationProcessorPaths>
	</configuration>
</plugin>